# ==========================================================================
# Pipeline Metagenomics - Configuration
# ==========================================================================

# Chemins des données
path:
  data_raw: "data/raw/"
  metadata: "data/metadata/metadata.tsv"
  taxonomy_ncbi: 
    zip_url: "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.zip"
    dmp_name: "data/taxonomy_ncbi"
  taxonomy_megahit: "data/taxonomy_megahit/taxname.txt"
  taxonomy_bakta: 
    local_path: "data/taxonomy_ncbi"
    url : "https://rest.kegg.jp/get/br:ko00001"
  physico_params: "data/physico_parameters/parameters.xlxs"
  gff3: "data/gff3"

extensions :
  reads: ".txt"       #".kaijuNR"
  contigs: ".txt"       #".tsv"
  bakta: ".txt"       #".gff3"
  plot: ".pdf"

save:
  rds_reads: "../results/"
  rds_contigs: ""
  rds_kegg: ""
  parquet_reads: ""
  parquet_contigs: ""
  parquet_kegg: ""
################
# Run parameters
################
# --- Modules actifs ---
run_taxonomy:     true
run_reads:        true
run_contigs:      true
run_kegg:         true
run_plots:        true
run_deseq2:       true
run_phyloseq:     true
run_physico:      true
run_qc:           true

####################
# General parameters
####################
deseq_label: "Genus"  # Options possibles : "Contig_ID", "Phylum", "Genus", etc.

# Reads parameters
reads:
  count_threshold: 10
  top_n: 19
  noise: "bacteria"

# Contigs parameters
contigs:
  length_threshold: 3000
  abundance_threshold: 1000
  rpkm_threshold: 0.5

# Kegg parameters
kegg:
  pvalue_threshold : 0.05
  lfc_treshold : 1.3

####################
# Graphic parameters
####################
#utile ?
taxonomic_levels:
  - "Phylum"
  - "Class"
  - "Order"
  - "Family"
  - "Genus"
  - "Species"

pathway_levels:
  - "level_1"
  - "level_2"
  - "level_3"
  - "gene_description"

plots:
# Global
  shared:
    theme: "theme_minimal"
    palette: "Turbo"
    width: 10
    height: 8
    title:
      size: 12
    legend:
      size: 10
    axes:
      size: 10

# Plots
  barplot:
    top_n: 19
    taxon_rank: "Class"

  barplot_taxonomy:
    top_n: 19
    taxon_rank: "Class"

  stackedbarplot:
    top_n: 19
    taxon_rank: "Class"

  pca:
    color_by: "condition"
    point_size: 2
    top_n: 10
    dim_x: 1
    dim_y: 2
    physico_cols: "pH"

  heatmap:
    top_n: 50
    clust_method: brad
    #cluster_rows: True

  run_volcano:
    pvalue_threshold : 0.05
    lfc_treshold : 1.3
