# ==========================================================================
# Pipeline MicrobExplorer
# Configuration file (YAML format)
# Author: "Yann Le Bihan"
# Date: "2025-12-01"
# Link : https://github.com/Yann-LBH/MicrobExplorer
#
# extensions used for input:
#  reads: kaijuNR
#  contigs: tsv
#  bakta: gff3
# ==========================================================================

# ==========================================================================
# PIPELINE CONFIGURATION - Change these parameters to customize the pipeline
# ==========================================================================

language: "en" # english (en) or français (fr)

# --- MODULES ACTIFS ---
# Choose True/False

run_taxonomy:     True
run_reads:        True
run_contigs:      True
run_kegg:         True
run_plots:        False
run_deseq2:       False
run_phyloseq:     False
run_pca:          False
run_physico:      False
run_qc:           False
run_shiny:        False

# DATA TYPES CONFIGURATION

datatypes:
  phyloseq: ["reads","contigs", "kegg"]
  deseq2: ["contigs", "kegg"]
  stackedbarplot:
    standard:
      pathway_relative: ["kegg"]
      relative_by_sample: ["reads", "contigs"]
      absolute_global: ["reads", "contigs"]
    deseq2:    ["contigs", "kegg"]
  heatmap: ["reads", "contigs", "kegg"]
  volcano: ["contigs", "kegg"] #k
  pca: ["reads", "contigs", "kegg"]
  qc: ["reads", "contigs", "kegg"]


# TREATEMENT PARAMETERS

reads:
  count_threshold: 10
  noise: 
    - "root"
    - "cellular organisms"
    - "unclassified"
    - "Bacteriophage sp."
    - "Duplodnaviria"
    - "environmental Halophage eHP-30"
    - "Methanobacterium virus PhiF1"
    - "Prokaryotic dsDNA virus sp."
    - "Riboviria"
    - "uncultured virus"
    - "Virus NIOZ-UU157"
    - "Viruses"

contigs:
  length_threshold: 3000
  abundance_threshold: 100
  rpkm_threshold: 0.5

kegg:
  pvalue_threshold : 0.05
  lfc_threshold : 1.3


# ANALYSIS PARAMETERS

# DESeq2 contrasts to generate
# Change this list to use only the contrasts you need
deseq2:
  contrast: ["ref", "date", "combo"]  # Options: "ref", "date", "combo"
  ref: "TD1" # enter your key ref, it will use all sample with this key as ref
  sizefactor: "poscounts" # Options: "poscounts", "ratio", "iterate"
  test: "Wald" # Options: "Wald", "LRT"
  fittype: "parametric" # Options: "parametric", "local", "mean"


# GRAPHIC PARAMETERS

plots:
# Global
  shared:
    theme: "theme_minimal"
    palette: "turbo"
    pdf_size: [12, 10] # [width, height]
    title_size: 12
    subtitle_size: 10
    legend_size: 12
    axes_size: 12
    rank:
      reads: "species" #eg : "domain", "kingdom", "phylum", class", "order", "family", "genus", "species"
      contigs: "species" #eg : "domain", "phylum", class", "order", "family", "genus", "species"
      kegg: "level_3" #eg : "level_1", "level_2", "level_3", "gene_description"

# Plots
  barplot:
    top_n: 19

  stackedbarplot:
    top_n: 10

  stackedbarplot_deseq2:
    title: "{source} | Top {top_n} {feature_type} differentially abundant in {contrast}"
    subtitle: "Pvalue threshold : {padj_threshold} | Log2 Fold Change threshold : {lfc_threshold} | {rank}"
    top_n: 10
    contrasts_values: # use the same order as your contrasts OPTIONS: "ref", "date", "combo"
      padj_threshold : ["0.01", "0.001", "0.01"]
      lfc_threshold : ["1.3", "1.3", "1.3"]

  heatmap:
    title: "{source} | Abundance of the top {top_n} taxons in sample {sample}"
    subtitle: "Hierarchical clustering: {clust_method} | Distance metric: {distance_method} | {rank}"
    top_n: 50
    clust_method: "ward.D2" # Options: "ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"
    distance_method: "bray" # Options: "euclidean", "maximum", "manhattan", "canberra", "binary", "minkowski"

  pca:
    title: "{source} | Principal Component Analysis (PCA) — {top_n} Most Variable Taxa"
    subtitle: "Ordination based on CLR distance | DIMENSION {dim_x} vs DIMENSION {dim_y} | {rank}"
    top_n: 10
    dim_x: 1
    dim_y: 2
    physico_col: "pH" # use any parameters from the physico_parameters file
    point_size: 2

  volcano:
    title: "{source} | Top {top_n} Differential Abundance Volcano Plot in {contrast}"
    subtitle: "Pvalue threshold : {padj_threshold} | Log2 Fold Change threshold : {lfc_threshold} | {rank}"
    top_n: 10
    contrasts_values: # use the same order as your contrasts OPTIONS: "ref", "date", "combo"
      padj_threshold : ["0.01", "0.001", "0.01"]
      lfc_threshold : ["1.3", "1.3", "1.3"]

# ==========================================================================
# DATA PATH - Do not modify
# ==========================================================================
samples_file: "config/samples.tsv"
title_resolver: "config/title.json"

input_path:
  data_raw: 
    reads: "data/raw/reads/"
    contigs: "data/raw/contigs/"
    kegg: "data/raw/kegg/"
  metadata: "data/metadata/metadata.xlsx"
  taxonomy_ncbi: 
    zip_url: "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.zip"
    dmp_name: "data/taxonomy_ncbi/new_taxdump.zip/rankedlineage.dmp"
    local_path: "data/taxonomy_ncbi/taxaname.tsv"
  taxonomy_megahit:
    original: "data/taxonomy_megahit/contigs_coassembly-taxNames.tsv"
    converted: "data/taxonomy_megahit/taxaname.tsv"
  pathway_bakta: 
    url : "https://rest.kegg.jp/get/br:ko00001"
    local_path: "data/pathway_bakta/pathway.tsv"
  physico_params: "data/physico_parameters/parameters.xlsx"

output_path:
  treatment: "results/treatment/"
  plots: "results/plots/"
  rds: "results/rds/"
  parquet: "results/parquet/"
  qc: "results/qc/"
  audit: "results/audit/final_MicrobExplorer_audit.html"
# ==========================================================================